### PR TITLE
Fix #103

### LINKED ISSUE #103: Vector `length` problem does not produce a message if there are no unique missing values
``` r
library(tblcheck)

.result   <- c(3, 4, 3)
.solution <- c(3, 4, 3, 4, 3)
vec_grade_length()
#> <gradethis_graded: [Incorrect] >
```

<sup>Created on 2021-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by rossellhayes**
``` r
library(tblcheck)

.result   <- c(3, 4, 3)
.solution <- c(3, 4, 3, 4, 3)
vec_grade_length()
#> <gradethis_graded: [Incorrect]
#>   Your result should contain 5 values, but it has 3 values.
#> >
```

<sup>Created on 2021-12-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Closes #103.

### CODE REVIEW

File: R/check_dimensions.R [hunk 1]
```diff
@@ -216,6 +216,10 @@ tblcheck_message.length_problem <- function(problem, ...) {
     }
   }
 
+  if (!length(problem$value)) {
+    return(glue::glue_data(problem, problem$exp_msg, problem$obj_msg))
+  }
+
   glue::glue_data(problem, problem$exp_msg, problem$obj_msg, problem$value_msg)
```
Comment (gadenbuie) [inline R/check_dimensions.R:223]: What if this were...?

```suggestion
  glue::glue_data(
    problem, 
    problem$exp_msg, 
    problem$obj_msg, 
    if (!length(problem$value)) problem$value_msg else ""
  )
```

or also this version?

```suggestion
  if (!length(problem$value)) {
    # remove values message: obj and exp have the same values but different length
    problem$value_msg <- ""
  }

  glue::glue_data(problem, problem$exp_msg, problem$obj_msg, problem$value_msg)
```

I like that these versions bring the focus to the `value_msg` and highlight that `exp_msg` and `obj_msg` don't change.

**Review by gadenbuie — APPROVED** [review]
LGTM! One small comment that you can take or leave
