### PR TITLE
Fix #118

### LINKED ISSUE #118: `tbl_grade_class()` can give unhelpful messages for grouped and rowwise tables
`tbl_grade_class()` suggests using `group_by()`, `ungroup()`, or `rowwise()` whenever `.result` or `.solution` is a grouped or rowwise tibble, even if the other isn't even a data frame.

``` r
library(dplyr)
library(tblcheck)

.result <- 1:2
.solution <- tibble(a = 1, b = 2) %>% group_by(b)

tbl_grade_class()
#> <gradethis_graded: [Incorrect]
#>   Your table isn't a grouped data frame, but I was expecting it to be
#>   grouped. Maybe you need to use `group_by()`?
#> >
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If the student failed to even create a data frame, failing to use `group_by()` is not the most actionable feedback.

### PR DESCRIPTION
**Pull request by rossellhayes**
`tbl_grade_class()` now only suggests using functions like `group_by()`, `rowwise()` or `ungroup()` if both `.result` and `.solution` are at least data frames.

``` r
library(dplyr)
library(tblcheck)

.result <- 1:2
.solution <- tibble(a = 1, b = 2) %>% group_by(b)
tbl_grade_class()
#> <gradethis_graded: [Incorrect]
#>   Your result should be a grouped tibble (class `grouped_df`), but it
#>   is a vector of integers (class `integer`).
#> >

.result <- tibble(a = 1, b = 2)
.solution <- tibble(a = 1, b = 2) %>% group_by(b)
tbl_grade_class()
#> <gradethis_graded: [Incorrect]
#>   Your table isn't a grouped data frame, but I was expecting it to be
#>   grouped. Maybe you need to use `group_by()`?
#> >
```

<sup>Created on 2022-08-08 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Closes #118.

### CODE REVIEW

File: R/check_class.R [hunk 1]
```diff
@@ -157,18 +157,15 @@ tblcheck_message.class_problem <- function(problem, ...) {
...
-  list <- hinted_class_message_list()
-
-  for (i in seq_along(list)) {
+  for (query in hinted_class_message_list()) {
     if (
-      all(list[[i]]$obj_class %in% obj_class) &&
-        all(list[[i]]$exp_class %in% exp_class)
+      # If `query$obj_class()` or `query$exp_class()` are empty,
+      # any class will match because `all(logical(0)) == TRUE`
+      all(query$obj_class %in% obj_class) && all(query$exp_class %in% exp_class)
```
Comment (gadenbuie) [inline R/check_class.R:164]: This comment raised questions, but now that I've re-read the code a bit, here's how I would summarize:

```r
# We provide hinted messages when the classes on obj/exp match the set of
# classes for the hint. The obj/exp class hint might be empty, indicating
# that we should ignore the class for that object. The use of `all()`
# accounts for both situations since `all(logical(0))` returns `TRUE`.
```

**Review by gadenbuie — COMMENTED** [review]
Looks great, just a couple of minor notes

File: R/check_class.R [hunk 2]
```diff
@@ -157,18 +157,15 @@ tblcheck_message.class_problem <- function(problem, ...) {
 }
 
 hinted_class_message <- function(obj_class, exp_class) {
-  list <- hinted_class_message_list()
-
-  for (i in seq_along(list)) {
+  for (query in hinted_class_message_list()) {
```
[the remark this answers is not in the document]
Comment (rossellhayes) [reply R/check_class.R:160]: Thanks, I updated this in f9bdd0a

File: R/check_class.R (hunk 1 above)
Comment (rossellhayes) [reply R/check_class.R:164]: Also incorporated in f9bdd0a
